### ISSUE TITLE
Indirect Spatial Datasets

### ISSUE THREAD

**Issue by Bfrichet2** [INSPIRE-MIF/helpdesk#10]
Hello,

I hope you are all right at JRC.

I work fort the Blegian Land Register Administration. I  am trying to create metadata about statistics concerning real estate transactions. These will be indrect spatial datasets. These are not really considered by the TG 2.0 for the implementation of INSPIRE datasets. 

My concerns are about the linking of such a dataset to a the datasets containing the dataset. I will write in the summaray where the readers can find the dataset containing the geometric features. I want to write in a machine readable XML element  the id of the record describing the dataset containing the geometric features.

I was thinking about adding a gmd:aggregationInfo with the uuid of the record. It would be something like this.

Does JRC have recommandation concerning this ? Did you get any other feedback from another administration ?

  <gmd:aggregationInfo>
            <gmd:MD_AggregateInformation>
               <gmd:aggregateDataSetIdentifier>
                  <gmd:MD_Identifier>
                     <gmd:code>
                        <gco:CharacterString>fb1e2993-2020-428c-9188-eb5f75e284b9</gco:CharacterString>
                     </gmd:code>
                  </gmd:MD_Identifier>
               </gmd:aggregateDataSetIdentifier>
               <gmd:associationType>
                  <gmd:DS_AssociationTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#DS_AssociationTypeCode"
                                              codeListValue="geometricFeatures"/>
               </gmd:associationType>
            </gmd:MD_AggregateInformation>
         </gmd:aggregationInfo>

**Comment by sMorrone** [comment]
@Bfrichet2 
it seems that the data you want to create metadata for is not falling under INSPIRE, so you are not obliged to use the INSPIRE MD TG 2.0 (latest version however is[ v2.1](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc)) to document it. No related _"feedback from another administration"_ has ever been posted in this helpdesk. That said, should you wish to use the INSPIRE TG to create your metadata, you might think of using the [Resource Locator element](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc#313-distribution-info-section). I proceed to close this issue as not INSPIRE-relevant, but feel free to re-open /create a new one should you have INSPIRE-reated questions.

**Comment by bfrichet3** [comment]
Dear 

I am quite suprised you needed one year to give me such an answer.Furthermore as indirect spatial datasets do fall under the scope of INSPIRE datasets: consequently it seems clear to me that metadata TG 2.0 should be able to answer to that question.

Regards

**Comment by sMorrone** [comment]
@Bfrichet2 
apologies for the brusqueness of the previous posting, my focus was more on the legal requirements and it seems I somehow oversaw your point. The Use Case you propose, extending the mandatory INSPIRE datasets with additional non-spatial data linked to the INSPIRE data / metadata is quite interesting.
However, there are some issues in your proposed realization - i.e. DS_AssociationTypeCode list does not contain the value "geometricFeatures". From a first scan, maybe the types "DS_AssociationTypeCode_crossReference" or "DS_AssociationTypeCode_partOfSeamlessDatabase" would better suit your purpose?
However, though no other similar requests have come to this helpdesk, maybe you are now aware of other organizations attempting the same approach? Ideally, should there be other data providers attempting this novel approach one could start thinking about proposal of a Good Practice.
If this is still relevant for you, could you be so kind as to open a new posting with a clearer title, e.g. Linking non-spatial data to INSPIRE

**Comment by bfrichet3** [comment]
@sMorrone 
It's okay for your answer. I totally agree with your answer: we should find a common solution that suits to european institutions. That's why I asked that question here because I though you had heard about that problem before. As it appears you haven't, I will investigate with other belgian institutions and I will ask to our representative to MIG-T to speak about that.

Regards,

**Comment by sMorrone** [comment]
@Bfrichet2 
looking forward to possible feedback !
