### ISSUE TITLE
D2.8.I.6 Data Specification on Cadastral Parcels – Technical Guidelines: UML graph

### ISSUE THREAD

**Issue by bfrichet3** [INSPIRE-MIF/helpdesk#108]
Dear

I cannot find anything concerning the administrativeunit role in the UML of Data Spécification on Cadastral Parcels though they are clearly included in both the text of the same Data Specification and the Regulation 1089/2010. Maybe we should add that association in the UML graph.

![image](https://user-images.githubusercontent.com/80756452/176713092-8222cb7b-bb88-4e17-85e6-b786297f9cbc.png)

Regards,

**Comment by heidivanparys** [comment]
Both BasicPropertyUnit and CadastralParcel have an association with AdministrativeUnit, and indeed, none of these are documented in the UML diagrams in the data specifications.

@bfrichet3 Could you please create a change proposal for the data specification of Cadastral Parcels at https://github.com/INSPIRE-MIF/technical-guidelines/ for this? See also the [README.md file](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/README.md) of that repository for more information about change proposals and the workflow for them, and follow the instructions you get when [creating a new issue](https://github.com/INSPIRE-MIF/technical-guidelines/issues/new/choose) there.

**Comment by sMorrone** [comment]
I am now closing this issue to avoid having same topic reported twice.  To follow evolution of the change proposal, please refer to linked issue https://github.com/INSPIRE-MIF/technical-guidelines/issues/50
