### ISSUE TITLE
How to provide codes for noise in HH?

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk#11]
Hi,

In July 2019, Stefania mentioned which noise codelists to use to provide noise data in INSPIRE HH in [this forum discussion](https://wayback.archive-it.org/12090/20210119172409/https://inspire.ec.europa.eu/forum/discussion/view/261192/envhealthdeterminantmeasure-how-to-express-the-type-of-noise-measure)
Unfortunately, the second page of this thread can not be loaded any longer in the archived version.
She is also relating to a change proposal which I guess is described [here](https://wayback.archive-it.org/12090/20210123030533/https://inspire.ec.europa.eu/forum/discussion/view/268807/provision-of-noise-exposure-delineation-priority-datasets-under-the-human-health-and-safety-data-theme-environmental-health-determinant-measure-spatial-objects).
According to the [UML diagram](https://inspire.ec.europa.eu/data-model/approved/r4618-ir/html/EARoot/EA2/EA3/EA9/EA1/EA8347.htm), the NoiseSourceTypeValue should be made available in a UomNoise object.
As the HH xsd uses gml:MeasureType for EnvHealthDeterminantMeasure.measure (discussed in [this forum post](https://wayback.archive-it.org/12090/20210122023724/https://inspire.ec.europa.eu/forum/discussion/view/53288/environmental-noise-directive)) and there such is no occurrence of UomNoise, it is still not clear to me how to indicate a link to the Eionet codelist in the INSPIRE HH schema.
Could someone please indicate where to put the Eionet codes or provide an example where this is realized?

Thanks and all the best

Johanna

**Comment by sMorrone** [comment]
Hi Johanna,
you simply **cannot** provide the _NoiseSourceTypeValue_ with the current HH schema. As stated in the [Forum post](https://wayback.archive-it.org/12090/20210119172409/https://inspire.ec.europa.eu/forum/discussion/view/261192/envhealthdeterminantmeasure-how-to-express-the-type-of-noise-measure) you mentioned above, the noise source issue has been addressed in a relevant IR Change Proposal for the ‘EnvHealthDeterminantMeasure’ spatial object type.

Stefania

**Comment by sMorrone** [comment]
Just one clarification regarding your statement "_She is also relating to a change proposal which I guess is described_ [here](https://wayback.archive-it.org/12090/20210123030533/https://inspire.ec.europa.eu/forum/discussion/view/268807/provision-of-noise-exposure-delineation-priority-datasets-under-the-human-health-and-safety-data-theme-environmental-health-determinant-measure-spatial-objects)": the mentioned post relates to the mapping of the **_Noise Exposure delineation_** **Priority Datasets** under the Human Health and Safety data theme **using the** **current schema**. More specifically the post provides mapping examples for the _measureTime_  and the _validFrom_ and _validTo_ elements already aligned with the recommendations in the revised END reporting 
Hope this helps
Stefania

**Comment by JohannaOtt** [comment]
Hi Stefania,

Ok, thanks for the quick reply and the helpful information. I wondered if I had missed that information somehow. Then I will move on without providing the NoiseSourceTypeValue.

All the best

Johanna

**Comment by JohannaOtt** [comment]
Hi @sMorrone ,

Do you already have any insights on when it is planned to realize the changes from the accepted Change Proposal in the draft and/or endorsed xsd files?


All the best

Johanna

**Comment by sMorrone** [comment]
Hi @JohannaOtt ,
the revised IR has not been adopted yet, also waiting for the outcomes of mandatory evaluation of the INSPIRE Directive by January 2022. Meanwhile, a relevant INSPIRE Good Practice proposal by EEA is being drafted and plan is to submit it to MIG-T by June. The EEA is also drafting a Good Practice proposal for the use of geopackage as alternative encoding for the END spatial data (submission planned by June as well).

Stefania

**Comment by Kate-Lyndegaard** [comment]
Hi Stefania,

Is there any news here? Was the INSPIRE Good Practice proposal by the EEA submitted? Is it available?

**Comment by sMorrone** [comment]
Hi Kate,
given the new governance process for the INSPIRE artefacts and the creation of the [repository to manage the changes to the INSPIRE XML schemas](https://github.com/INSPIRE-MIF/application-schemas), it was decided not to create a Good Practice proposal. An issue was instead opened in the above repository (https://github.com/INSPIRE-MIF/application-schemas/issues/6) and it has been directly assigned the "for Comitology" label, meaning that the change proposal was already endorsed by the MIG and is going through the Comitology procedure.
