### ISSUE TITLE
GeographcialName: sourceOfName

### ISSUE THREAD

**Issue by bfrichet3** [INSPIRE-MIF/helpdesk#110]
Dear

I hope you are all right. I noticed something quite ennoying concerning sourceOfName attribute of GeographcialName feature type. As you may know that attribute aims to describe in a human readable way the source of a GeographicalName object.

![image](https://user-images.githubusercontent.com/80756452/177338121-42bfbe64-a068-4400-9488-fa67008f54d5.png)

Regulation 1089/2010 states that field has to be filled with a CharacterString object. That kind of objects aims to express some human readable in one language. As you may know in Belgium we do have three national languages. Even for a Dutch name (for instance "Antwerpen") I do have to express the sourceOfName attribute in both Dutch and French to comply with belgian legislation: the language of the GeographicalName itself does not matter.

I know this is an official  Regulation so it is quite complicate to change it but it would be more suitable to allow LocalisedCharacterString objects instead of CharacterString.

Do you think that something could be done?

Regards

**Comment by fabiovinci** [comment]
Dear @bfrichet3,

I think that if you want to specify the `sourceOfName` in different languages it is better to use multiple occurrences of the main attribute, to have each `sourceOfName` together with the related `language`.

What is the data theme you are using?

**Comment by bfrichet3** [comment]
Dear

Thank you for your answer.  I am working on Administrative Units theme. Unfortunately this solution is not convenient enough. 

For instance Brussels do have official spelling in French (Bruxelles) and in Dutch (Brussel). I have to right in both French and Dutch the sourceOfName of Dutch name and French Name. It is quite clear in belgian national law.

Regards

**Comment by bfrichet3** [comment]
as far as I understand it, the language tag aims to identify the language of o geographical name and not of its description

![image](https://user-images.githubusercontent.com/80756452/178018944-04411dad-2771-46ce-b4c2-d9274d35c843.png)

**Comment by sMorrone** [comment]
Dear @bfrichet3 , the issue you have to face is quite clear and, as you correctly say, its solution requires a change in the IR and consequently in the GN data specification.  Should you wish, you can propose a change to the Geographical Names TG related to the GeographicalName data type by opening an issue in the [TG repository](https://github.com/INSPIRE-MIF/technical-guidelines). The proposal will then follow the governance and release process detailed in [this document](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/governance-release-process/process.md).

**Comment by bfrichet3** [comment]
dear @sMorrone , thank you for your answer. I will right propose such a change. Will that workflow lead to a modification of regulation 1089/2010?  As I understand it, it is not enought to modify TG, we have to modify the underlying regulation.

Regards

**Comment by bfrichet3** [comment]
dear @sMorrone ,

Thank you for your answer. I will create an issue as you say.

Regards and merry christmas
