### ISSUE TITLE
Mineral resources question

### ISSUE THREAD

**Issue by apfelnymous** [INSPIRE-MIF/helpdesk#111]
Hello, I dont understand the Commodity --> MineralOccurence "source" relationship, its 1. So if there is a commodity sulphur it only can only be found at one deposit ?

**Comment by sMorrone** [comment]
Dear @apfelnymous ,
the "Commodity" feature type is meant to describe the material of economic interest in a specific deposit. Through the "Commodity" feature type you can specify  the level of importance of the deposit for a specific commodity and the commodity rank related to a deposit (using the commodityImportance and the commodityRank elements respectively). So, for example, if you want to specify that sulfur can be found in two different deposits,  you have to create two instances of the "Commodity" feature type, each linking to the related deposit.

**Comment by apfelnymous** [comment]
> So, for example, if you want to specify that sulfur can be found in two different deposits, you have to create two instances of the "Commodity" feature type, each linking to the related deposit.
@sMorrone thx I needed to hear that from someone else.
