### ISSUE TITLE
Different statements on additional Layers for HH.HealthDeterminantMeasure in IR and DS

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk#13]
According to Article 14.3 of the [IR](https://eur-lex.europa.eu/legal-content/en/TXT/PDF/?uri=CELEX:02010R1089-20141231&qid=1585807762468&from=DE), multiple layers depending on codelist values should only be provided for types, for which it is explicitely expected in the Annex by the use of specific placeholders etc:  "3. For spatial object types whose objects can be further classified using a code list-valued attribute, several layers may be defined. Each of these layers shall include the spatial objects corresponding to one specific code list value. In the definition of such sets of layers in Annexes II, III and IV, all of the following requirements shall be fulfilled: (a) the placeholder <CodeListValue> shall represent the values of the relevant code list, with the first letter in upper case; (b) the placeholder <human-readable name> shall represent the human-readable name of the code list values; (c) the spatial object type shall include the relevant attribute and code list, in parentheses; (d) one example of a layer shall be given"
For HH.HealthDeterminantMeasure, this is not the case:
![grafik](https://user-images.githubusercontent.com/34163838/108496520-76ea3780-72aa-11eb-813f-40c07ece22f3.png)

I would interpret that in a way that no further classification of HH.HealthDeterminantMeasure layers is expected.

The [DS for Human Health and Safety](https://inspire.ec.europa.eu/file/1537/download?token=Uk33dqjm) states in 11.1 that the HH layers can be further classified: "NOTE The table above contains several layers for some spatial object type(s), which can be further classified using a code list-valued attribute. Such sets of layers are specified as described in Article 14(3) of the IRs" (No grey template paragraph but explicit HH content)

To me, that is contradictory to the IR. Could you please specify what is expected here?

PS: I am aware of the [discussion on adding additional, independent layers to WMS](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39), but I want to know if there are sub-layers of HH.HealthDeterminantMeasure expected/allowed and if yes, if there are expectations on which code list-values attribute they should use for distinction.

**Comment by sMorrone** [comment]
Dear @JohannaOtt,
sub-layers of HH.HealthDeterminantMeasure expected/allowed (though not mandatory) are based on values in the https://inspire.ec.europa.eu/codelist/EnvHealthDeterminantTypeValue codelist. 

Stefania

**Comment by JohannaOtt** [comment]
@sMorrone Thank you for the input. Can they only be provided as sub layers? So would it also be allowed to have a WMS only serving `HH.HealthDeterminantMeasure.noise` or does the WMS necessarily need to procide `HH.HealthDeterminantMeasure` with `HH.HealthDeterminantMeasure.noise` being a sub layer of it?

**Comment by sMorrone** [comment]
@JohannaOtt , it need not be a sub-layer.

**Comment by sMorrone** [comment]
@JohannaOtt was you question fully answered. Can we proceed with closing this issue?

**Comment by JohannaOtt** [comment]
@sMorrone Yes, I'd say so. If I run into issues again, I will open a new issue.
