### ISSUE TITLE
Status of INSPIRE Coverage Good Practice

### ISSUE THREAD

**Issue by KathiSchleidt** [INSPIRE-MIF/helpdesk#14]
Status of INSPIRE Coverage Good Practice
All further discussions will be linked from here

**Comment by KathiSchleidt** [comment]
related to #22

**Comment by heidivanparys** [comment]
The good practice on coverages was endorsed at the [13th MIG meeting](https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=778175536), can this issue be closed?

**Comment by heidivanparys** [comment]
Closing this issue, see https://github.com/INSPIRE-MIF/helpdesk/issues/22#issuecomment-868682492.
