### ISSUE TITLE
Can't find a link to requirement classes

### ISSUE THREAD

**Issue by PB-GNM** [INSPIRE-MIF/helpdesk#141]
At
https://github.com/INSPIRE-MIF/gp-ogc-api-features/blob/master/spec/oapif-inspire-download.md#83-requirements-class-inspire-oapif-geojson-
The link to the requirement class does not work:
http://inspire.ec.europa.eu/id/spec/oapif-download/1.0/req/geojson does not give a result.
The same counts for the other requirement classes.

I also posted this problem at:
https://github.com/INSPIRE-MIF/gp-ogc-api-features/issues/86
But this repository does not seem to be very active, so that is why I also post this at the central helpdesk.

Does anyone know where these requirement classes might have moved to?

Best regards,
Pieter Bresters

**Comment by heidivanparys** [comment]
The HTTP-URIs for the requirements classes haven't been made resolvable (yet?), that means that so far, they are only used as identifiers for the requirements classes.

![image](https://user-images.githubusercontent.com/11427611/205241565-933091b7-fce6-4095-88d2-2b9a5982ddfa.png).

Ideally, http://inspire.ec.europa.eu/id/spec/oapif-download/1.0/req/geojson would resolve and be redirected to https://github.com/INSPIRE-MIF/gp-ogc-api-features/blob/master/spec/oapif-inspire-download.md#83-requirements-class-inspire-oapif-geojson-

**Comment by heidivanparys** [comment]
This issue was answered in https://github.com/INSPIRE-MIF/gp-ogc-api-features/issues/86 and can therefore be closed.
