### ISSUE TITLE
Query on the legalFoundationDocument attribute related to the spatial data theme Protected Sites

### ISSUE THREAD

**Issue by tarts001** [INSPIRE-MIF/helpdesk#15]
Would appreciate guidance on the approach to take in those instances when the legal act that created a specific Protected Site is repealed and replaced by a new legislative instrument.

**Comment by sMorrone** [comment]
Dear @tarts001 ,
no data updating action required. The act that created the PS is the repealed one, so this is the legal act to be mentioned in the legalFoundationDocument attribute.

**Comment by sMorrone** [comment]
Dear @tarts001 
has your question been fully answered? ? do you still have doubts or can we consider this issue closed?

Stefania

**Comment by tarts001** [comment]
@sMorrone - Yes, my concern has been answered. Thank you for your support.
