### ISSUE TITLE
INSPIRE validator / monitoring support for legal compliance with Data-Service linking simplification

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk#154]
Dear INSPIRE EC team, 

in connection to the support for the [Data-Service Linking Simplification](https://inspire.ec.europa.eu/good-practice/data-service-linking-simplification), can we assume, if such approach is implemented in member state, it can be considered as legally compliant?

If so, does EC Reference validator supports data service linking?
Similarly, will upcoming INSPIRE monitoring period support such approach in calculation of the monitoring indicators?

Finally, does that mean, that [INSPIRE linkage checker](https://inspire-geoportal.ec.europa.eu/linkagechecker.html) is not needed anymore, if such approach is implemented?

Thank you,

Best regards, 

Martin Tuchyna, Slovakia

**Comment by jescriu** [comment]
Dear @MartinTuchyna,

Thank you for your question, which is indeed very relevant. 

As @heidivanparys wrote above, we are facing the initial steps to process the necessary changes to the TGs that needs to be updated (TG Metadata, TG View services, TG Download services - for WFS and ATOM) to accommodate this INSPIRE Good Practice. This will be channelled through the MIWP Sub-group 2.3.1 - managing the INSPIRE artefacts.

In the meantime, we are right now starting a procurement to implement (between others) the good practice in the INSPIRE Geoportal GeoNetwork console, and we will coordinate the necessary changes to the INSPIRE Reference Validator tests, according the schedule of this procurement.

However, I can anticipate you that we cannot commit to have it ready for the next Monitoring and Reporting exercise.

In the following months we will face the rollout of the revamped INSPIRE Geoportal (based on the GeoNetwork backend), currently undergoing security testing. Once the rollout is successfully achieved, we will proceed phasing out all the components of the Classic INSPIRE Geoportal (currently not maintained), including the INSPIRE linkage checker.

All components will be gradually replaced by functionalities based on GeoNetwork.

**Comment by MartinTuchyna** [comment]
Thank you, @jescriu
