### ISSUE TITLE
Procuction and Industrial Facilities

### ISSUE THREAD

**Issue by hhorppila** [INSPIRE-MIF/helpdesk#16]
Are the first-level Eurostat NACE rev. 2 classification categories B, C, D, E, F and H enough to produce harmonised Production and Industrial Facilities data set? In Finland municipalities may not have more detailed information content according to the EconomicActivityNACEValue code list.

Kind regards,
Hanna Horppila

**Comment by sMorrone** [comment]
Dear @hhorppila ,
yes, first-level Eurostat NACE rev. 2 classification categories B, C, D, E, F and H are enough, if you do not have more detailed info. Of course, use values in the EconomicActivityValue code  list to refer the categories e.g. https://inspire.ec.europa.eu/codelist/EconomicActivityNACEValue/B 

Kind regards,
Stefania

**Comment by sMorrone** [comment]
Dear @hhorppila,
has your question been fully answered? ? do you still have doubts or can we consider this issue closed?

Stefania

**Comment by hhorppila** [comment]
Dear @sMorrone,
thank you for your help! Yes, you can close this issue. I am sorry that my response was delayed due to my absence. 

Kind regards,
Hanna
