### ISSUE TITLE
Access to the INSPIRE Monitoring Indicators – Guidelines Document

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk#165]
Dear INSPIRE team,

could you please check availability of this document via new INSPIRE knowledge forum website:
https://knowledge-base.inspire.ec.europa.eu/publications/inspire-monitoring-indicators-guidelines-document_en 

When trying to access the document via [Download](https://knowledge-base.inspire.ec.europa.eu/document/download/2089dac2-535e-4b9b-9cbe-9f04a6506952_en) hyperlink request is redirected to the [landing page](https://knowledge-base.inspire.ec.europa.eu/index_en). 

Similarly, trying to use [Google memory option](https://webcache.googleusercontent.com/search?q=cache:RGcsGIpRnk8J:https://inspire.ec.europa.eu/documents/inspire-monitoring-indicators-%25E2%2580%2593-guidelines-document-0&hl=sk&gl=sk&client=firefox-b-d).

Thanks, Martin

**Comment by fabiovinci** [comment]
Dear @MartinTuchyna,

thank you for the notification, we will fix it asap.

In the meantime, you can find the document in the archived version of the old IKB: https://wayback.archive-it.org/12090/20230905163413/https:/inspire.ec.europa.eu/documents/inspire-monitoring-indicators-%E2%80%93-guidelines-document-0

**Comment by fabiovinci** [comment]
Dear @MartinTuchyna,

the issue was fixed, and the document is now available on the new IKB.

**Comment by MartinTuchyna** [comment]
Dear @fabio

Thanks for re-publishing of the document.
