### ISSUE TITLE
Error in schemaLocation (ShapeChangeAppinfo.xsd) - parked domain

### ISSUE THREAD

**Issue by axza** [INSPIRE-MIF/helpdesk#17]
I'm currently using /hh/4.0/HumanHealth.xsd in deegree and this morning the following error message appeared:

`Error building GML application schema: Severe error in schema document (systemId: http://portele.de/ShapeChangeAppinfo.xsd, line: 1, column: 50) White spaces are required between publicId and systemId.`

In above mentioned schema, these import fails:

```
<import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo" schemaLocation="http://portele.de/ShapeChangeAppinfo.xsd"/>
```

It seems the domain name has been expired and was not renewed:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <style type="text/css">
            html, body, #partner, iframe {
                height:100%;
                width:100%;
                margin:0;
                padding:0;
                border:0;
                outline:0;
                font-size:100%;
                vertical-align:baseline;
                background:transparent;
            }
            body {
                overflow:hidden;
            }
        </style>
        <meta content="NOW" name="expires">
        <meta content="index, follow, all" name="GOOGLEBOT">
        <meta content="index, follow, all" name="robots">
        <!-- Following Meta-Tag fixes scaling-issues on mobile devices -->
        <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" name="viewport">
    </head>
    <body>
        <div id="partner"></div>
        <script type="text/javascript">
            document.write(
                    '<script type="text/javascript" language="JavaScript"'
                            + 'src="//sedoparking.com/frmpark/'
                            + window.location.host + '/'
                            + 'IONOSParkingDE'
                            + '/park.js">'
                    + '<\/script>'
            );
        </script>
    </body>
</html>
```

**Comment by axza** [comment]
The following schemes are also affected

base2/BaseTypes2.xsd
bu-base/4.0/BuildingsBase.xsd
ge-core/4.0/GeologyCore.xsd
ge_gp/4.0/GeophysicsCore.xsd
ge_hg/4.0/HydrogeologyCore.xsd
hh/hh.xsd
omop/3.0/ObservableProperties.xsd
sr/4.0/SeaRegions.xsd

**Comment by KathiSchleidt** [comment]
Hiya,
no idea why that's included all over, just sent a note to Clemens to please make available again
:)

**Comment by cportele** [comment]
Oops, I wasn't aware that there are still active references to that file. I did some updates to my server and did some clean-up. I have now restored the file. Sorry, for any inconvenience. 

As part of the update, the server now redirects from http to https. I hope that does not cause any issue to parsers. If it does, let me know and I will see, if I can configure an exception for that file.

By the way, the canonical URL of the file is https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd

**Comment by fabiovin** [comment]
It seems that neither deegree nor the INSPIRE Reference Validator are able to handle the redirection to https.

I think it would be better to temporarily restore the http schema until the INSPIRE schemas are updated with the new https link.

**Comment by cportele** [comment]
@fabiovin - I have added the exception, please try again.

**Comment by axza** [comment]
Ahoi @cportele 
unfortunately the exception is not catched by deegree - ended up using a local copy as workaround

also pinging @trf42
#https://github.com/deegree/deegree3/issues/1064#issuecomment-797376595

**Comment by cportele** [comment]
Maybe there is a cache involved? The exception works for every request by any client.

**Comment by fabiovin** [comment]
I confirm that since this morning both deegree and the validator work fine

**Comment by axza** [comment]
> Maybe there is a cache involved? The exception works for every request by any client.
restartet tomcat - that was it, works again as usual

**Comment by axza** [comment]
Issue resolved - thanks to all of you!
