### ISSUE TITLE
Link to INSPIRE reference validator from IKB

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk#174]
Dear INSPIRE Team,

could you please check the link for INSPIRE reference validator on the landing page of the [INSPIRE knowledge base](https://knowledge-base.inspire.ec.europa.eu/index_en)?

![obrázok](https://github.com/INSPIRE-MIF/helpdesk/assets/6195936/d75e6de2-b082-4a40-801c-24aeef6d6004)

Seems there is some issue as its navigating on specific port https://inspire.ec.europa.eu:8090/validator/ instead of https://inspire.ec.europa.eu/validator/home/index.html

![obrázok](https://github.com/INSPIRE-MIF/helpdesk/assets/6195936/66af0bf4-db95-4d93-965e-fd3f9e3266ec)

Thanks, Martin and Kinga

**Comment by fabiovinci** [comment]
Dear @MartinTuchyna,

thank you for the notification, we will fix it asap.

**Comment by fabiovinci** [comment]
Dear @MartinTuchyna,

we have corrected the link, thanks again for reporting.

**Comment by MartinTuchyna** [comment]
Great, thanx, m
