### ISSUE TITLE
Staging INSPIRE Reference Validator - Verification CAPTCHA Failure

### ISSUE THREAD

**Issue by Kunhulta** [INSPIRE-MIF/helpdesk#188]
Dear INSPIRE Team, 

we have noticed, that the verification process (captcha) on the Staging INSPIRE Reference Validator website is not working properly. 
The verification failed even after providing a correct answer. 
Could you please look into this matter? 
Thanks in advance,

Kinga
![image](https://github.com/INSPIRE-MIF/helpdesk/assets/164530825/34679717-2a65-449d-99e0-0d26cc22e780)

**Comment by fabiovinci** [comment]
Dear @Kunhulta,

thank you for notifying us.
We are already working on a similar issue in the Validator Helpdesk (https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1047).
Please refer to it to stay updated on the progress.
