### ISSUE TITLE
Transport Network Air - AirLinkSequence - clarification request

### ISSUE THREAD

**Issue by kgaeb** [INSPIRE-MIF/helpdesk#19]
Dear all,
the TN-A Schema for AirLinkSequence requires an ordered list of AirRouteLink elements. Unfortunately the dataType Network::DirectedLink allows only "+" and "-" for the attribute "direction".
But in reality the AirRouteLink elements of an AirRoute can be flown inDirection, inOppositeDirection or in bothDirections as described in the LinkDirectionValue.
Currently we don't see a possibility to use the attribute LinkDirectionValue in the transport network air model, which would make more sense to us. Instead we have to use the dataType Network::DirectedLink as plus or minus sign. This makes the AirLinkSequence and AirRoute not only complicated, this forces us to replicate AirRouteLink elements in the AirLinkSequence and therefore making the AirLinkSequence nearly unuseable.
Can someone please advice us how to encode it correctly?
Thanks and kind regards
Klaus

**Comment by sMorrone** [comment]
@kgaeb 
did the provided reply help you? can we close this issue?
