### ISSUE TITLE
MIG-T website is down

### ISSUE THREAD

**Issue by oberseri** [INSPIRE-MIF/helpdesk#195]
The MIG-T website is down, which prevents us from getting the today's meeting URL

**Comment by jescriu** [comment]
Dear @oberseri,

The server went down for some reason.

Hereby you have the meeting link to access the meeting:
https://ecconf.webex.com/ecconf-en/j.php?MTID=mfd51f8e4c62e15c048071259b6fd0245 

And the Agenda:
[78_MIG-T_Meeting-Agenda.pdf](https://github.com/INSPIRE-MIF/helpdesk/files/15344980/78_MIG-T_Meeting-Agenda.pdf)

**Comment by oberseri** [comment]
Thanks @jescriu !
