### ISSUE TITLE
Environmental Management Facilities - problem with transformation scheme

### ISSUE THREAD

**Issue by JulianaKar** [INSPIRE-MIF/helpdesk#20]
Hello, 
I am applying for the Utility and Governmental Services Theme Environmental Management Facilities part data transformation. The scheme to transform these data is  https://inspire.ec.europa.eu/schemas/us-emf/4.0/EnvironmentalManagementFacilities.xsd, but after the data transformation and export,  information is not transferred to the GML file. Only an empty result is created (added).
[US_EMF.zip](https://github.com/INSPIRE-MIF/helpdesk/files/6180616/US_EMF.zip)
The same result is created with the older version too (https://inspire.ec.europa.eu/schemas/us-emf/3.0/EnvironmentalManagementFacilities.xsd).
I did not find any previous discussion about this question, is there a chance that the scheme could be updated?

**Comment by sMorrone** [comment]
Hello @JulianaKar ,
you are right! The us-emf application schema in the official repository is missing the type definition  for the element "EnvironmentalManagementFacility" . This means that, using the official schema, it is not possible to provide the environmental management facilities spatial objects.  You can find more details and have access to a shared fixed schema in the following post from the (now dismissed) INSPIRE Community Forum: 
https://wayback.archive-it.org/12090/20210119192050/https://inspire.ec.europa.eu/forum/discussion/view/265816/error-in-the-environmental-management-facilities-application-schema. 
You could try the downloadable fixed schema https://wayback.archive-it.org/12090/20210119192050/http://cloud.epsilon-italia.it/INSPIRE/EnvironmentalManagementFacilities.xsd and feedback here if it works fine for you (as it did for me). Your feedback could be precious to speed up official fixes in the official  INSPIRE schema repository.  

Stefania

**Comment by JulianaKar** [comment]
Thank you for your help. The scheme you provided suited me perfectly.

Juliana

**Comment by sMorrone** [comment]
Issue is linked to change proposal [#4](https://github.com/INSPIRE-MIF/application-schemas/issues/4) in the [INSPIRE XML schemas GitHub repository](https://github.com/INSPIRE-MIF/application-schemas)
