### ISSUE TITLE
Registry Namespaces can no longer be resolved

### ISSUE THREAD

**Issue by jane-heller-bkg** [INSPIRE-MIF/helpdesk#202]
**URI:** https://inspire.ec.europa.eu/ids

**Motivation:** In Germany, we use the URI `https://inspire.ec.europa.eu/ids` for an INSPIRE object ID in the WFS (without versioning). An example is as follows:

```
<gml:identifier codeSpace="https://inspire.ec.europa.eu/ids">https://registry.gdi-de.org/id/de.ni.mein_namensraum/lokalerIdentifikator</gml:identifier>

<ge:inspireId>
  <base:Identifier xmlns:base="http://inspire.ec.europa.eu/schemas/base/3.3">
    <base:localId>lokalerIdentifikator</base:localId>
    <base:namespace>https://registry.gdi-de.org/id/de.ni.mein_namensraum/</base:namespace>
  </base:Identifier>
</ge:inspireId>
```

It has come to our attention that the namespace `https://inspire.ec.europa.eu/ids` can no longer be resolved.

However, this namespace is still mentioned in Annex H (informative): Implementation of Identifiers using URIs in INSPIRE:

"This is not a complete guide to URI implementation. Additional information can be found in Annex of D2.7 v3.3 and on the INSPIRE website at http://inspire.ec.europa.eu/ids."

As sufficiently detailed in the document INSPIRE Generic Conceptual Model: [Link](https://knowledge-base.inspire.ec.europa.eu/document/download/bb551703-c8ab-4fbd-a556-f7cf75feabe3_en?filename=d2.5_v3.4.pdf), a link should be persistent and unambiguous.

Therefore, we are questioning why this is not the case for the codespace `https://inspire.ec.europa.eu/ids`.

**Proposed change:** We kindly request clarification on why the codespace can no longer be resolved and what the proposed alternative will be.
**Change Type:** Clarification

**Comment by fabiovinci** [comment]
Dear @jane-heller-bkg,

thank you for noticing this.

We will implement a redirect to the correspondent page of the old IKB website: https://wayback.archive-it.org/12090/20161219023749/http:/inspire.ec.europa.eu/ids

**Comment by fabiovinci** [comment]
Dear @jane-heller-bkg,

we have implemented the redirect.

Please feel free to test it and report any issues you may find.
