### ISSUE TITLE
Custom ExtendedCapabilities elements not supported

### ISSUE THREAD

**Issue by fhoubie** [INSPIRE-MIF/helpdesk#24]
We are testing our service against the validation tool for "View Services - WMS and WMTS (TG version 3.11)". The endpoint of our service is : http://sdidemo.intergraph.pl/WMS_Iowa/service.svc/get?request=GetCapabilities&service=WMS

We use an extension in an ExtendedCapabilities element, but the validator does not seem to accept it. It does not accept it for the UserDefinedSymbolization either.

The test report is here : https://inspire.ec.europa.eu/validator/v2/TestRuns/EID31ce68a2-4469-41b2-8172-32a1724e16f1.html

Is that something not valid for INSPIRE View service or an error in the validator ?
Thanks

**Comment by MarcoMinghini** [comment]
This issue was originally opened in the [Validator helpdesk](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/). We moved it here, since it addresses a more general INSPIRE discussion topic and is not Validator-specific.

**Comment by fhoubie** [comment]
@MarcoMinghini, here is another URL : http://sdidemo.intergraph.pl/WMS_INSPIRE/service.svc/get?request=GetCapabilities&service=WMS

**Comment by fabiovinci** [comment]
Dear @fhoubie,

this issue should be solved by the following schema change, "[Add SLD capabilities schema to inspire_vs.xsd schema](https://github.com/INSPIRE-MIF/application-schemas/issues/51)", already endorsed and released.

Could you please check and confirm?
Thanks

**Comment by fabiovinci** [comment]
Dear @fhoubie,

since the WMS services you provided as an example are no longer available, we cannot test them.

Since the issue should be solved, I'm closing now the issue.

Please reopen the issue or open a new one in the Validator Helpdesk if the problem persists.
