### ISSUE TITLE
Are WPS NS or not?

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk#26]
According to the INSPIRE Directive are WPS Network Services or not?

![image](https://user-images.githubusercontent.com/20813598/95647831-3cda7f00-0adb-11eb-8e8a-b4155d6a8310.png)

If the question should be rephrased or extended, then:

There is any reason why in the validator & ATS there are no tests for WPS?

And/Or:

There is any reason why in the validator & ATS there are no tests for the harmonized SDSs (except for testing their metadata)?

According to https://inspire.ec.europa.eu/documents/position-paper-implementing-rules-inspire-services-allowing-spatial-data-services-be-0

![image](https://user-images.githubusercontent.com/20813598/95731632-70a6d780-0c88-11eb-9896-65d31af63b1c.png)

However 5 years later in https://inspire.ec.europa.eu/id/document/tg/sds is mentioned:

![image](https://user-images.githubusercontent.com/20813598/95717722-0c7b1800-0c76-11eb-9a79-2f713915a409.png)

**Comment by MarcoMinghini** [comment]
This issue was originally opened in the [Validator helpdesk](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/). We moved it here, since it addresses a more general INSPIRE discussion topic and is not Validator-specific.

**Comment by iuriemaxim** [comment]
Indeed this question is still open.

**Comment by heidivanparys** [comment]
From #5 :

> I have no experience with WPS, but depending on the exact processes it implements, I guess a specific installation could be categorised
>   - as a [transformation service](http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/transformation)
>   - as an [invoke service](http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/invoke)
>   - as a [service that is neither a discovery, view, download, transformation or invoke service](http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/other).

Note that the [beta instance of OGCs TEAM Engine](https://cite.opengeospatial.org/te2/) has an [ETS for WPS](https://github.com/opengeospatial/ets-wps10). If/when the ETS will be ready, it will be moved to the [production instance](https://cite.opengeospatial.org/teamengine/). For questions regarding the ETS, please contact OGC using the information on https://github.com/opengeospatial/ets-wps10.

If there is enough interest, a request could perhaps be submitted to the validator people to add a that test to the INSPIRE validator as well (if I remember correctly, also the WFS test partly or fully uses the OGC TEAM Engine).

And an additional note: OGC is working on new standards, also regarding processes, see https://ogcapi.ogc.org/processes/.

**Comment by heidivanparys** [comment]
@iuriemaxim 

I think that a better answer than what is written in the comments is hard to give at this point. Please note that the Commission would like to hear your view on the INSPIRE Directive, feedback is possible up to and including the 12th of July 2021, see more on https://ec.europa.eu/info/law/better-regulation/have-your-say/initiatives/12427-Sharing-geospatial-data-on-the-environment-evaluation-INSPIRE-Directive-_en. I will therefore close this issue for now (the related #1 is still open).
