### ISSUE TITLE
Harmonization of air quality data (INSPIRE theme III/5 HH)

### ISSUE THREAD

**Issue by fantamir** [INSPIRE-MIF/helpdesk#28]
According to the INSPIRE data specifications, **air quality data** are part of the **INSPIRE theme III/5 Human Health and Safety**. As described in the **D2.8.III.5 Data Specification on Human Health and Safety – Technical Guidelines** document (e.g. pages 25 - 26) and in the INSPIRE feature catalogue, a raw measurement data should be stored in the EnvHealthDeterminantMeasure object and a statistical data resulting from aggregation of raw measurements in the EnvHealthDeterminantStatisticalData object.

To simplify the problem description, let's imagine the source spatial dataset (set of points or grid network) has following attributes:
pollutantSpecification
pollutantConcentration  
pollutantUnitOfMeasure
pollutantTimeInformation  (sampling date)
pollutantMedia  (e.g. air)

Then, in the process of data harmonisation with the INSPIRE III/5 theme data structure, the source data attributes should be mapped as follows:
pollutantSpecification -> UomConcentration - component, 
pollutantMedia -> UomConcentration - media, 
pollutantUnitOfMeasure - UomConcentration - uom
pollutantConcentration -> EnvHealthDeterminantMeasure - measure, 
pollutantTimeInformation ->  EnvHealthDeterminantMeasure - measureTime

I use HALE>>studio for harmonisation of our data with INSPIRE and creation of harmonised GML files. Unfortunately, in this case I cannot find the way how to interlink the EnvHealthDeterminantMeasure and UomConcentration objects. Could somebody provide me any hint or sample of harmonised data? 

Thank you very much
Miroslav Fanta
CENIA, Czech Environmental Information Agency

**Comment by sMorrone** [comment]
Dear @fantamir ,
neither the ‘**component**’ nor the ‘**media**’ of the concentration can be provided using the current HH schema (as well it is not possible to provide the noise source - see issue [#11](https://github.com/INSPIRE-MIF/helpdesk/issues/11)). 
This problem has been addressed in an IR change proposal for the spatial object type "EnvHealthDeterminantMeasure”, implying of course relevant changes in the HH schema. 
However if the air quality data you are referring to are those related to the environmental reporting (so, if we are talking about the related Priority Dataset), you might consider the mapping to the EF data theme proposed in the  [list of priority datasets v2.1 final](https://webgate.acceptance.ec.europa.eu/fpfis/wikis/download/attachments/299729499/eReporting_PriorityDataList_V2.1_final_withcomments_20201008.xlsx?version=1&modificationDate=1602228162165&api=v2)

Stefania

**Comment by sMorrone** [comment]
Regarding the  IR change proposal for the spatial object type "EnvHealthDeterminantMeasure”,  please see https://github.com/INSPIRE-MIF/helpdesk/issues/11#issuecomment-874804863
