### ISSUE TITLE
metadataURL in Layer WMS

### ISSUE THREAD

**Issue by trodin** [INSPIRE-MIF/helpdesk#30]
Question about MatadataURL element in Layer element in the WMS Capabilities document: There should be exactly one MetadataURL per layer or is it possible to have more than one MetadataURL inside one Layer element?

Thank you,
Tanja

**Comment by trodin** [comment]
I mean this for child layer. One child layer element- one metadataURL?

**Comment by heidivanparys** [comment]
Short answer: yes, it is possible to have more than one `MetadataURL` inside one `Layer` element.

Long answer:

From the [WMS specification](https://portal.ogc.org/files/?artifact_id=14416):

```
<element name="Layer">
<annotation>
<documentation>
Nested list of zero or more map Layers offered by this server.
</documentation>
</annotation>
<complexType>
<sequence>
<element ref="wms:Name" minOccurs="0"/>
<element ref="wms:Title"/>
<element ref="wms:Abstract" minOccurs="0"/>
<element ref="wms:KeywordList" minOccurs="0"/>
<element ref="wms:CRS" minOccurs="0" maxOccurs="unbounded"/>
<element ref="wms:EX_GeographicBoundingBox" minOccurs="0"/>
<element ref="wms:BoundingBox" minOccurs="0" maxOccurs="unbounded"/>
<element ref="wms:Dimension" minOccurs="0" maxOccurs="unbounded"/>
<element ref="wms:Attribution" minOccurs="0"/>
<element ref="wms:AuthorityURL" minOccurs="0" maxOccurs="unbounded"/>
<element ref="wms:Identifier" minOccurs="0" maxOccurs="unbounded"/>
<element ref="wms:MetadataURL" minOccurs="0" maxOccurs="unbounded"/>
<element ref="wms:DataURL" minOccurs="0" maxOccurs="unbounded"/>
<element ref="wms:FeatureListURL" minOccurs="0" maxOccurs="unbounded"/>
<element ref="wms:Style" minOccurs="0" maxOccurs="unbounded"/>
<element ref="wms:MinScaleDenominator" minOccurs="0"/>
<element ref="wms:MaxScaleDenominator" minOccurs="0"/>
<element ref="wms:Layer" minOccurs="0" maxOccurs="unbounded"/>
</sequence>
<attribute name="queryable" type="boolean" default="0"/>
<attribute name="cascaded" type="nonNegativeInteger"/>
<attribute name="opaque" type="boolean" default="0"/>
<attribute name="noSubsets" type="boolean" default="0"/>
<attribute name="fixedWidth" type="nonNegativeInteger"/>
<attribute name="fixedHeight" type="nonNegativeInteger"/>
</complexType>
</element>
```

(note the `maxOccurs="unbounded"` for `wms:MetadataURL`)

and

```
<element name="MetadataURL">
<annotation>
<documentation>
A Map Server may use zero or more MetadataURL elements to offer
detailed, standardized metadata about the data underneath a
particular layer. The type attribute indicates the standard to which
the metadata complies. The format element indicates how the metadata is structured.
</documentation>
</annotation>
<complexType>
<sequence>
<element ref="wms:Format"/>
<element ref="wms:OnlineResource"/>
</sequence>
<attribute name="type" type="NMTOKEN" use="required" />
</complexType>
</element>
```

From https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224#tocId18:

> If the resource is a spatial data service, this metadata element identifies, where relevant, the target spatial data set(s) of the service through their unique resource identifiers (URI).

Note the plural: spatial data set(**s**).

From https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02008R1205-20081224#tocId50:

> | 1.6 | Coupled resource | 0..* | Mandatory if linkage to data sets on which the service operates are available. |

Again, plural: 0..*

(the "Coupled resource" is expressed in the MetadataURL: see the [TG on view services](https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-view-services-1):

![image](https://user-images.githubusercontent.com/11427611/122127395-62224880-ce33-11eb-8fd9-1f949c19e7be.png)
)

**Comment by heidivanparys** [comment]
@trodin I hope that the answer provided has helped you. I'll close the issue, but feel free to re-open it in case you have additional questions.
