### ISSUE TITLE
Implementing recommended theme-specific metadata elements

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk#37]
Hi,

I am interested in implementing the recommended theme-specific metadata elements outlined in section 8.3 of INSPIRE data specifications, specifically those related to data quality.

In section 8.3 of the protected sites data specification, for example, there are a list of optional metadata
elements including:

Logical Consistency – Conceptual Consistency 0..* 
Logical Consistency – Domain Consistency 0..* 
Completeness – Commission 0..* 
Completeness – Omission 0..* 

In Data Quality section 7.13 of the protected sites data specification it is stated that:

"_The Application Schema conformance class of the Abstract Test Suite in Annex I defines a number of tests to evaluate the conceptual consistency (tests A.1.1-A.1.9) of a data set_."

and in section 7.14 it is stated that:

"_The Application Schema conformance class of the Abstract Test Suite in Annex I defines a number of tests to evaluate the domain consistency (tests A1.10-A.1.12) of a data set._"

If a dataset passes these tests, is that sufficient to report in the associated data quality metadata elements?

Regarding the completeness of a dataset- are there any existing resources which describe the test criteria that could be used to determine commission and omission for a dataset (number of excess or missing features)?

Any feedback would be greatly appreciated.

Kind regards,
Kate

**Comment by sMorrone** [comment]
Dear @Kate-Lyndegaard,
the INSPIRE Validator **theme-specific** ETSs can be used to evaluate both the **conceptual consistency** (count of all items in the dataset that are not compliant with the rules of the conceptual schema) and the **domain consistency** (count of all items in the dataset that are not in conformance with their value domain). Therefore passing these successfully is sufficient to report in the associated data quality metadata elements.

**Comment by sMorrone** [comment]
@Kate-Lyndegaard was your question fully answered? Can we proceed with closing this issue?

**Comment by Kate-Lyndegaard** [comment]
Hi @sMorrone, yes, my question was answered. Thank you very much.
