### ISSUE TITLE
Hierarchical INSPIRE Land Use Classification System (HILUCS): state of play, any revision planned?

### ISSUE THREAD

**Issue by stearnold** [INSPIRE-MIF/helpdesk#40]
Dear all, 
has the codelist of the Inspire land use classes been revised recently, since its implementation, respectively are there any plans or content-wise reasons to do so?

**Comment by sMorrone** [comment]
Dear @stearnold 
the (non extensible) HILUCS code list has not been revised, and, at least to my knowledge, there are no plans to do so.
