### ISSUE TITLE
Inspire core concepts

### ISSUE THREAD

**Issue by Ceprey2** [INSPIRE-MIF/helpdesk#43]
Hello everybody,
It is quite hard to find some terms and concepts strict definitions: attribute name, feature (not only feature type, but also feature itself), attributes names, rules for attributes names. Is there a way to find these definitions in an official document?
Thanks in advance

**Comment by sMorrone** [comment]
Dear @Ceprey2 ,
general terms and definitions that specify the common terminology used in the INSPIRE Directive and in the INSPIRE Implementing Rules documents can be found in the [**INSPIRE glossary**](https://inspire.ec.europa.eu/glossary) (very useful the Search bar … e.g. type in _feature concept_ and a list of related entries will appear).
You will find definitions related to common concepts also in the [**D2.5: Generic Conceptual Model**](https://inspire.ec.europa.eu/documents/inspire-generic-conceptual-model). For example, in the _Terms and abbreviations_  section you can find the definition of the _feature_ you were asking for  
![image](https://user-images.githubusercontent.com/13329248/125263101-07c9ba00-e303-11eb-8498-fa0402f749e8.png)

Data theme specific definitions can be found in _Terms and definitions_ sections of the related Data Specifications.

**Comment by Ceprey2** [comment]
Thank you, sMorrone, indeed it is a very detailed one, just what I've been searching for.

**Comment by sMorrone** [comment]
Perfect! I will then close this issue, but please feel free to re-open should you have any additional doubts.

**Comment by KathiSchleidt** [comment]
A bit more info for the deeply interested - here a valuable resource for the underlying ISO definitions that the INSPIRE models were built upon:
https://isotc211.geolexica.org/concepts/

**Comment by Ceprey2** [comment]
KathiSchleidt, thank you so much for this valuable source.
