### ISSUE TITLE
Empty themes in UML diagram

### ISSUE THREAD

**Issue by Ceprey2** [INSPIRE-MIF/helpdesk#44]
Hello everybody,
What does it mean if a theme is not clickable, does not show up in the diagram, like it is the case for "Coordinate Reference System" https://inspire.ec.europa.eu/data-model/approved/r4618-ir/html/ ? Is the UML schema available for it?
![CoordRefSystem](https://user-images.githubusercontent.com/25895406/126616499-d77eb8fe-57a9-4e86-b79e-488812b6c948.jpg)

**Comment by sMorrone** [comment]
Dear @Ceprey2 ,
Coordinate reference systems and Geographical grid systems establish requirements and recommendations related to the provision of INSPIRE data sets from other INSPIRE (data) themes. In other words, RS and GG themes govern the rules for providing, accessing and visualising data sets in the scope of INSPIRE, but they do not mandate the provision of themes-specific data themselves. 
You will find more details in [this discussion](https://wayback.archive-it.org/12090/20210123132019/https://inspire.ec.europa.eu/forum/discussion/view/261694/is-it-necessary-to-set-up-services-for-the-coordinate-reference-systems-rs-and-the-geographical-grid-systems-gg-data-themes) from the INSPIRE Community Forum.
Hope this helps ...

**Comment by Ceprey2** [comment]
Thank you, I'll refer to this discussion then.
