### ISSUE TITLE
attributes "inspireId", "beginLifeSpanVersion", "endLifeSpanVersion" different behavior

### ISSUE THREAD

**Issue by Ceprey2** [INSPIRE-MIF/helpdesk#45]
Hi,
![AttributesBehaviour2AppSchemasEnergy](https://user-images.githubusercontent.com/25895406/126939086-938e26b3-8703-4d6a-882c-be8e6f24bc9a.JPG)

I've just noticed that the attributes in the application schemas "Energy Resources Vector" and "Energy Resource Coverage" of the UML Consolidated Model  do not get transformed into properties by ShapeChange, although other attributes do get transformed into properties in the resulting .ttl fie. What do you think could be the reason for that? How are these attributes different from all other attributes across the model?' Thanks in advance.

**Comment by heidivanparys** [comment]
@Ceprey2 Is it possible that this issue has been solved in https://github.com/ShapeChange/ShapeChange/issues/277?

**Comment by Ceprey2** [comment]
Yes, thank you.
