### ISSUE TITLE
Is "RequierementClass" an actually existing class?

### ISSUE THREAD

**Issue by Ceprey2** [INSPIRE-MIF/helpdesk#47]
Hi,
I'm trying to convert the application schema "WaterML20" from the UML consolidated model to a .ttl file with ShapeChange, but the generated ontology is almost empty (with no classes). My question is , do "Requirement Classes" really exist as types or classes in the diagram or they are just placeholders for some stereotypes?
![WaterML20](https://user-images.githubusercontent.com/25895406/126961223-b3b141a3-6c41-420e-b3ea-c0b1b03216e2.JPG)

**Comment by KathiSchleidt** [comment]
Could it be that you're trying to generate the following:
https://github.com/opengeospatial/NamingAuthority/blob/master/definitions/conceptschemes/waterml.ttl

I'd be interested at what data you plan on providing via WaterML in ttl! Also, if you provide the measurement data under INSPIRE, you should probably also provide the EnviromentalMonitoringFacility (INSPIRE Theme EF) for this - I'd be most interested at the ttl for that!

**Comment by Ceprey2** [comment]
Thank you, this ontology may be helpful, although it contains mainly individuals, no classes, but the can be added manually. Still not sure what data to put on it (we'll see in November with my students). Unfortunately, I did not succeed in generating EF, if I do, I'll post this .ttl here.

**Comment by KathiSchleidt** [comment]
@Ceprey2 do keep us informed what your students come up with! As for data, you may find more in OGC groups, e.g. Hydrology Domain Working Group: https://www.ogc.org/projects/groups/hydrologydwg
Also - while not yet semantically encoded, you can find some interesting water resources here: https://datacoveeu.github.io/API4INSPIRE/datanests/franco-germanic-flow.html

**Comment by Ceprey2** [comment]
Oh, thank you so much. Hope, we will come up with somethin interesting.
