### ISSUE TITLE
GEMET API availability

### ISSUE THREAD

**Issue by mhogeweg** [INSPIRE-MIF/helpdesk#6]
we are running into an issue frequently that the GEMET API are unavailable.

example:
https://www.eionet.europa.eu/gemet/getConceptsMatchingRegexByThesaurus?thesaurus_uri=http%3A%2F%2Fwww.eionet.europa.eu%2Fgemet%2Fconcept%2F&language=en&regex=water&jsonp=dojo_request_script_callbacks.dojo_request_script1

is this the right place to report such issues?

apologies for the cross-posting: https://github.com/INSPIRE-MIF/helpdesk-validator/issues/494

**Comment by sMorrone** [comment]
Dear @mhogeweg 
I am afraid this is not the right place to ask. The GEMET Thesaurus is managed by EEA, so not an INSPIRE asset. You might try opening an issue on the GEMET GitHub repository [(https://github.com/eea/gemet)](url)

**Comment by mhogeweg** [comment]
Thank you for your response. Submitted as suggested: https://github.com/INSPIRE-MIF/helpdesk/issues/7

**Comment by fabiovin** [comment]
Dear @mhogeweg,
the repository suggested by @sMorrone is: https://github.com/eea/gemet/issues

You posted the issue in this same repository ;-)
