### ISSUE TITLE
Is directly linking between EnvironmentalMonitoringNetwork and EnvironmentalMonitoringFacility without using the association class NetworkFacility allowed?

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk#63]
Hi there,

I have a question regarding the Environmental Monitoring Facility specification. Is directly linking between ```EnvironmentalMonitoringNetwork``` and ```EnvironmentalMonitoringFacility``` without using the association class ```NetworkFacility``` allowed?

UML: https://inspire.ec.europa.eu/data-model/approved/r4618-ir/html/index.htm?goto=2:3:6:1:1:7980

The Validator does not complain about the direct linking, however because ```NetworkFacility``` is not a feature type, deegree does not generate external ```GetFeatureById``` links for referencing the respective objects.

Example WFS: https://haleconnect.com/ows/services/org.874.512633c0-2899-4f9d-b2d1-1bd51cb2315a_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

**Comment by JohannaOtt** [comment]
Hi all,

I validated [this file](https://haleconnect.com/ows/services/org.874.512633c0-2899-4f9d-b2d1-1bd51cb2315a_wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&NAMESPACES=xmlns%28ef%2Chttp%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fef%2F4.0%29%2Cxmlns%28ompr%2Chttp%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fompr%2F3.0%29&TYPENAMES=ompr%3AProcess%2Cef%3AEnvironmentalMonitoringNetwork%2Cef%3AEnvironmentalMonitoringFacility) returned by the WFS Kate mentioned in the issue description with the ETS for EF that is now available. In the [result](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID4a37446b-55f0-4ce8-a282-53cdb549ec9f), there is no error on the NetworkFacility class not being used.
So the validator does not seem to expect it but the schema does?


All the best

Johanna

**Comment by KathiSchleidt** [comment]
The validator does not go into the details of what you link via xlink, you can put anything there, e.g. xlink:href="nonexistant.site.org/dummy"

I did a simple test file for ef:EnvironmentalMonitoringNetwork, added the ef:NetworkFacility, but then dead-ended the ef:contains & ef:belongsTo to point to "#bla" - validates just fine ;) See:
`https://gist.githubusercontent.com/KathiSchleidt/3103e46217d971dd5fa7217e650cf34b/raw/5f486d8707722fc85656cfb515bd108d49b4f36c/EF-XLink-Hack.gml
`

The issue with leaving out the ef:NetworkFacility will be with other applications expecting a correct data model, they'll probably stumble over the gap as they'll be expecting a ef:NetworkFacility where you provide ef:EnvironmentalMonitoringFacility

It comes down to your goal, is this just formal validation or potential reuse of harmonized data?

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

the answer to your question "_Is directly linking between EnvironmentalMonitoringNetwork and EnvironmentalMonitoringFacility without using the association class NetworkFacility allowed?_" is "Yes".

The additional attributes of the association `belongsTo`, defined by the association class _NetworkFacility_, are optional.

For this reason, the encoding present in your dataset is valid (as confirmed by Johanna):

`<ef:belongsTo xlink:href="#EnvironmentalMonitoringNetwork_OBS_L2"/>`

Let us know if you have further questions.
