### ISSUE TITLE
Schema us-nt-tc disappeared

### ISSUE THREAD

**Issue by LiesbethR** [INSPIRE-MIF/helpdesk#68]
This morning, the schema of us-net-tc disappeared from https://inspire.ec.europa.eu/schemas/.
When will it appear again?
Probably it is just a copy paste error (the schema is still available via https://inspire.ec.europa.eu/schemas/2021.1/).

**Comment by fabiovin** [comment]
Dear @LiesbethR,

since the application schema of _us-net-tc_ is not included in the IR but only proposed in the TG (so, it is out of legislation), it was moved to the draft schema repository https://inspire.ec.europa.eu/draft-schemas/us-net-tc/.

The official schemas repository (https://inspire.ec.europa.eu/schemas/) contains now the schemas related to the last release, i.e. 2021.2 (see also the [changelog](https://github.com/INSPIRE-MIF/application-schemas/releases)).

The previous versions of schemas are available in this folder: https://inspire.ec.europa.eu/schemas/2021.1.

**Comment by MarcoMinghini** [comment]
Dear @LiesbethR, 
as written by @fabiovin above:

> the schema was moved to the draft schema repository https://inspire.ec.europa.eu/draft-schemas/us-net-tc/

so you can now find it there.

> The previous versions of schemas are available in this folder: https://inspire.ec.europa.eu/schemas/2021.1.

This folder includes the previous version of the schemas, with the dependencies also updated so that existing implementations are not broken.

**Comment by LiesbethR** [comment]
So we have to refer to https://inspire.ec.europa.eu/schemas/2021.1/.
When will this version be deleted?

**Comment by MarcoMinghini** [comment]
You can either refer to the same schema (that was moved to the `draft-schemas` folder for the reasons explained above) or to the old schema, which will be preserved (also in the future, without being deleted) in the `2021.1` folder.

**Comment by LiesbethR** [comment]
We refer to the parent schema, because we need all the us-net schemas.

**Comment by LiesbethR** [comment]
> You can either refer to the same schema (that was moved to the `draft-schemas` folder for the reasons explained above) or to the old schema, **which will be preserved (also in the future, without being deleted) in the `2021.1` folder**.

That's a good thing, because our processes rely on that schema (6000-7000 validations per day).

**Comment by heidivanparys** [comment]
This issue is related to application-schemas#49:

> in the [release 2021.2](https://github.com/INSPIRE-MIF/application-schemas/releases/tag/2021.2) of the INSPIRE schemas, we moved all the non-endorsed INSPIRE schemas that were still present in the directory https://inspire.ec.europa.eu/schemas. In particular, the schema us-net-tc/4.0/TelecommunicationsNetwork.xsd was moved in the draft-schemas folder (https://inspire.ec.europa.eu/draft-schemas/us-net-tc/4.0/TelecommunicationsNetwork.xsd), in addition to being included in the folder https://inspire.ec.europa.eu/schemas/2021.1/ which includes all the schemas as they were before the 2021.2 release.
> 
> To still preserve the rule of having only official INSPIRE schemas in the https://inspire.ec.europa.eu/schemas directory and to avoid breaking existing implementations, we implemented a redirection from http://inspire.ec.europa.eu/schemas/us-net-tc/4.0/TelecommunicationsNetwork.xsd (which does not exist anymore) to https://inspire.ec.europa.eu/draft-schemas/us-net-tc/4.0/TelecommunicationsNetwork.xsd. This should solve the issue with schema validation.

@LiesbethR The redirection was verified in the Netherlands (@PalmJanssen).

As application-schemas#49 is closed, I will close this issue as well. Feel free to add any additional comments, or reopen again, if needed.
