### ISSUE TITLE
gmd:metadataStandardName and gmd:metadataStandardVersion in INSPIRE compliant metadata

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk#69]
Hi,

As INSPIRE-compliant dataset metadata is based on a profile of ISO 19115, does anything speak agains declaring conformity to ISO 19115 in the `gmd:metadataStandardName` and `gmd:metadataStandardVersion` elements? Along the same lines, can INSPIRE-complaint service metadata declare conformity to ISO 19119?

Kind regards,
Kate

**Comment by heidivanparys** [comment]
Nothing speaks against stating the name and version of the metadata standard used in the elements you mention:

```xml
  <gmd:metadataStandardName>
      <gco:CharacterString>ISO 19115</gco:CharacterString>
  </gmd:metadataStandardName>
  <gmd:metadataStandardVersion>
      <gco:CharacterString>2003</gco:CharacterString>
  </gmd:metadataStandardVersion>
```

```xml
  <gmd:metadataStandardName>
      <gco:CharacterString>ISO 19119</gco:CharacterString>
  </gmd:metadataStandardName>
  <gmd:metadataStandardVersion>
      <gco:CharacterString>2005</gco:CharacterString>
  </gmd:metadataStandardVersion>
```

**Comment by Kate-Lyndegaard** [comment]
Hi Heidi,

Super, thank you for the confirmation:-)

Kind regards,
Kate

**Comment by heidivanparys** [comment]
You're welcome 🙂.
