### ISSUE TITLE
GEMET API availability

### ISSUE THREAD

**Issue by mhogeweg** [INSPIRE-MIF/helpdesk#7]
we are running into an issue frequently that the GEMET API are unavailable. We reference this API in our INSPIRE metadata editors.

example:
https://www.eionet.europa.eu/gemet/getConceptsMatchingRegexByThesaurus?thesaurus_uri=http%3A%2F%2Fwww.eionet.europa.eu%2Fgemet%2Fconcept%2F&language=en&regex=water&jsonp=dojo_request_script_callbacks.dojo_request_script1

it may respond today but not tomorrow. 

Is it recommended to consume the API or perhaps to download the thesaurus and host with the application itself?

**Comment by MarcoMinghini** [comment]
Duplicates #6 which is already addressed and closed. In case of additional questions, please reopen that issue.
