### ISSUE TITLE
ISO srv schema imports non-existant schema URLs

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk#73]
Hi everybody,

This ISO [serviceMetadata.xsd](http://schemas.opengis.net/iso/19139/20070417/srv/1.0/serviceMetadata.xsd) imports two schemas which are not availeble (any longer?) at the indicated schemaLocations: "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd" and "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gco/gco.xsd".

This can cause issues when trying to use the [apiso metadata schema](http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd) used in INSPIRE because the problematic schema is recursively imported there as well.

I did not find a contact point at ISO for reporting such issues. Does anyone know where to report it or is there a direct contact between the INSPIRE community and ISO that could be used for that?

Thank you and all the best

Johanna

**Comment by heidivanparys** [comment]
All ISO/TC 211 schemas, including annotated documentation, are available at the [schema server of ISO/TC 211](https://schemas.isotc211.org/):

- [gmd](https://schemas.isotc211.org/schemas/19139/-/gmd/1.0/gmd.xsd)
- [gco](https://schemas.isotc211.org/19139/-/gco/1.0/gco.xsd)

See also https://github.com/ISO-TC211/XML (@ejbleys) for more information.

Regarding a contact point at ISO, there is a [standards tracker](https://github.com/ISO-TC211/StandardsTracker/issues) where you submit all issues. For more information about the standards tracker, see this [presentation](https://committee.iso.org/files/live/users/fh/aj/aj/tc211contributor%40iso.org/files/Presentations/2021-06%20Virtual/07_%20PMG_Parslow.pdf) and [this video](https://www.youtube.com/watch?v=-ch1qqo1wrs) by @PeterParslow.

Note that the serviceMetadata.xsd resides on the OGC schema server (@ogcscotts), not on the ISO/TC 211 schema server.

**Comment by JohannaOtt** [comment]
@heidivanparys Thank you for your reply. So would you recommend reporting this issue to OGC rather than to ISO?

**Comment by heidivanparys** [comment]
I checked again, and I actually think that you should be using the schemas from the ISO schema server directly, see https://schemas.isotc211.org/schemas/19119/.

But yes, for any issues regarding the OGC schema server, you should contact OGC indeed. This is a special case as it concerns schemas related to an ISO standard…

**Comment by JohannaOtt** [comment]
Hi Heidi,

Thank you for your quick replies.

> I actually think that you should be using the schemas from the ISO schema server directly, see https://schemas.isotc211.org/schemas/19119/.

As mentioned in my first comment, this issue is occuring when using the apiso schema because it imports these schemas recursively. So I cannot change the schemas being used unfortunately.

> But yes, for any issues regarding the OGC schema server, you should contact OGC indeed.

I contacted OGC know via the contact form on their homepage - hope that will help everyone to have an apiso schema available for which all imports are working.


All the best

Johanna

**Comment by heidivanparys** [comment]
> > I actually think that you should be using the schemas from the ISO schema server directly, see https://schemas.isotc211.org/schemas/19119/.
> 
> As mentioned in my first comment, this issue is occuring when using the apiso schema because it imports these schemas recursively. So I cannot change the schemas being used unfortunately.

Sorry, yes, you're right, apiso.xsd is only at the OGC server, so you can't use a more recent version from ISO there. I hope you'll get a quick reply from OGC.

**Comment by fabiovin** [comment]
Hello @Johannaott,

I don’t know with what tool you are encountering this issue, because even though the links in the serviceMetadata.xsd are not valid, the apiso.xsd is valid.
It is used by the Validator without problems.

**Comment by JohannaOtt** [comment]
@fabiovin I do not doubt that the apiso.xsd is valid but you can for example not load it in hale studio as it is expected that all imported schemas are available.

**Comment by fabiovin** [comment]
@JohannaOtt, ok, waiting for a fix by OGC, you can use this draft apiso schema (https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd), we created it when there was a problem with gmd and gmx schemas.
It works in hale studio.

**Comment by JohannaOtt** [comment]
@fabiovin Great, thank you for the info!
