### ISSUE TITLE
Webinar: Emerging Approaches for Data-Driven Innovation in Europe - Monday, January 24, 2022

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk#77]
# **ELISE Webinar: Emerging Approaches for Data-Driven Innovation in Europe - January 24th 14:00-16:00 CET (UTC+1)**

The digital transformation of the European economy and society is framed by the European strategy for data that foresees the establishment of a common European data space based on domain-specific data spaces in strategic sectors such as environment, agriculture, industry, health and transportation.

Acknowledging the key role that emerging technologies and innovative approaches for data sharing and use can play to make European data spaces a reality, the webinar will present the results of a set of experiments and research conducted by a pool of experts, which are part of  the upcoming JRC report “Emerging Approaches for Data-Driven Innovation in Europe”.

Coordinated by the Digital Economy Unit of the [European Commission's Joint Research Centre (JRC)](https://ec.europa.eu/jrc/en), the experts investigated emerging technologies, innovative approaches for data sharing and use, and socio-technical factors that occur in data-driven innovation in the geospatial field.

The team from the Digital Economy Unit of the JRC will introduce the report and set the scene from the scientific and policy perspective. In the three subsequent sessions the experts will present and discuss their work.
 
**More details**: https://joinup.ec.europa.eu/node/704912

**Registration**: https://us02web.zoom.us/meeting/register/tZ0rdOuqrzkiE9IgY7aG0al18itApU2FUrZb

## **Agenda**

**Presentation of the report and scene setting from a scientific and policy perspective** - Alexander Kotsev, Marco Minghini, Marina Micheli & Sven Schade, _European Commission, JRC_; Carlos Granell, _Universitat Jaume I de Castellón, Spain_

**Session 1. Innovative approaches to data sharing**

* Introduction to the session
  * **Combining public sector and citizen-generated data - the case of addresses**, Alessandro Sarretta, _National Research Council, Italy_
   * **Binary serialisation for static and dynamic data**, Peter Mooney, _Maynooth University, Ireland_
   * **Enforcing automation in building, testing and deployment of software applications – the case of cloud-based data services**, Just van den Broecke, _OSGeo.nl, The Netherlands_
* Discussion panel
* Science and policy takeaways 

**Session 2. IoT and decentralised architectures**

* Introduction to the session
  * **Processing data close to its origin - edge computing on IoT devices**, Frank Ostermann, _University of Twente, The Netherlands_
  * **Event-driven architectures for data exchange**, Simon Jirka & Matthes Rieke, _52°North Spatial Information Research GmbH_
* Discussion panel
* Science and policy takeaways 

**Session 3. The social and organisational dimensions of data-driven innovation**

* Introduction to the session
  * **Addressing public-private partnership for data supply – data collaboratives for air quality in cities**, Stefaan Verhulst, _The GovLab, New York University, US_
  * **Understanding demand for data-driven innovation in the public sector – the case of algorithmic processes**, Lina Dencik, _Cardiff University_; Marina Micheli, _European Commission - JRC_
  * **Aligning EU-level policies and local practices in the advent of European data spaces**, Hillen Oost, _Association of Dutch Municipalities / Futura Nova.eu, The Netherlands_
* Discussion panel
* Science and policy takeaways 

**Wrap-up and next steps**

**Comment by sMorrone** [comment]
Recording of the webinar and supporting slides are available [here](https://joinup.ec.europa.eu/collection/elise-european-location-interoperability-solutions-e-government/document/presentation-emerging-approaches-data-driven-innovation-europe)
