### ISSUE TITLE
Document URL of Normative Reference to GeoDCAT-AP is not working

### ISSUE THREAD

**Issue by ghobona** [INSPIRE-MIF/helpdesk#84]
The Document URL of Normative Reference to GeoDCAT-AP is not working.

The Document URL link is on this page https://inspire.ec.europa.eu/documents/geodcat-ap

![Screenshot 2022-04-14 at 07 21 30](https://user-images.githubusercontent.com/18121038/163326610-6f818e0c-ac67-498b-ad64-7cbf3d9fd29c.png)

**Comment by sMorrone** [comment]
Dear @ghobona, 
thank you for pointing this out.
@hernlor, @MarcoMinghini could you please have a look?
Thank you

**Comment by andrea-perego** [comment]
The URL to be used is the following: 

https://semiceu.github.io/GeoDCAT-AP/releases/

**Comment by sMorrone** [comment]
Dear @ghobona, 
URL has been modified. Could you please check that everything is correct, so that this issue can be closed? 
Thank you

**Comment by ghobona** [comment]
The link is now working. The issue can be closed. Thanks.
